version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: umconnect-sarrwin  # Specify custom image name and tag
    container_name: umconnect_sarrwin

    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: umconnect
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: umconnect
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
